export const steps = [
  { id: 1, title: "Account Information" },
  { id: 2, title: "Personal Information" },
  { id: 3, title: "Physical Attributes" },
  { id: 4, title: "Education & Occupation" },
  { id: 5, title: "Habits" },
  { id: 6, title: "Horoscope Details" },
  { id: 7, title: "Family Profile" },
];

export const CASTES = {
  hindu: [
    "Brahmin",
    "Kshatriya",
    "Vaishya",
    "Kayastha",
    "Maratha",
    "Rajput",
    "Gupta",
    "Agarwal",
    "Nair",
    "Ezhava",
    "Kumhar",
    "Yadav",
  ],
  muslim: [
    "Shia",
    "Sunni",
    "Ansari",
    "Khan",
    "Syed",
    "Pathan",
    "Sheikh",
    "Qureshi",
  ],
  christian: [
    "Roman Catholic",
    "Protestant",
    "Orthodox",
    "Pentecostal",
    "Baptist",
    "Evangelical",
  ],
  sikh: ["Jatt", "Khatri", "Ramgharia", "Arora", "Ahluwalia", "Majhabi"],
};

export const SUB_CASTES = {
  Brahmin: [
    "Kokanastha",
    "Deshastha",
    "Iyer",
    "Iyengar",
    "Namboodiri",
    "Madhwa",
    "Pandit",
    "Saraspur",
  ],
  Kshatriya: ["Bundela", "Chauhan", "Rathore", "Sisodia", "Tomar", "Rajawat"],
  Vaishya: ["Agarwal", "Gupta", "Maheshwari", "Oswal", "Baniya", "Jain"],
  Maratha: ["Kokanastha", "Deshastha", "Peshwa", "Patil"],
  Rajput: ["Sisodia", "Rathore", "Chauhan", "Tomar", "Shekhawat", "Bundela"],
};

export const LANGUAGES = [
  "Hindi",
  "Bengali",
  "Telugu",
  "Marathi",
  "Tamil",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Odia",
  "Assamese",
  "Urdu",
  "Maithili",
  "Sanskrit",
  "English",
];

export const STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Puducherry",
  "Chandigarh",
  "Ladakh",
  "Jammu & Kashmir",
];

export const DEGREES = [
  "B.Tech",
  "M.Tech",
  "BBA",
  "MBA",
  "MBBS",
  "MD",
  "BA",
  "MA",
  "BCA",
  "MCA",
  "B.Sc",
  "M.Sc",
  "Ph.D",
  "B.Ed",
  "M.Ed",
  "LLB",
  "LLM",
  "Diploma",
  "CA",
  "ICWA",
];

export const OCCUPATIONS = [
  "Software Engineer",
  "Doctor",
  "Teacher",
  "Business Owner",
  "Lawyer",
  "Accountant",
  "Government Employee",
  "Professor",
  "Architect",
  "Civil Engineer",
  "Consultant",
  "Nurse",
  "Researcher",
  "Data Scientist",
  "Artist",
  "Journalist",
];

export const NAKSHATRAS = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigashira",
  "Ardra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishta",
  "Shatabhisha",
  "Purva Bhadrapada",
  "Uttara Bhadrapada",
  "Revati",
];

export const RASHI = [
  "Mesh (Aries)",
  "Vrishabh (Taurus)",
  "Mithun (Gemini)",
  "Kark (Cancer)",
  "Sinh (Leo)",
  "Kanya (Virgo)",
  "Tula (Libra)",
  "Vrishchik (Scorpio)",
  "Dhanu (Sagittarius)",
  "Makar (Capricorn)",
  "Kumbh (Aquarius)",
  "Meen (Pisces)",
];

export const CITIES = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Tirupati",
  ],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang"],
  Assam: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"],
  Bihar: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia"],
  Chhattisgarh: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Raigarh"],
  Goa: ["Panaji", "Vasco da Gama", "Margao", "Mapusa", "Ponda"],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Gandhinagar",
    "Bhavnagar",
  ],
  Haryana: ["Gurugram", "Faridabad", "Panipat", "Ambala", "Rohtak", "Hisar"],
  "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala", "Kullu", "Solan"],
  Jharkhand: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh"],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Hubballi",
    "Mangaluru",
    "Belgaum",
    "Gulbarga",
  ],
  Kerala: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain"],
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane"],
  Manipur: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur"],
  Meghalaya: ["Shillong", "Tura", "Jowai", "Nongpoh"],
  Mizoram: ["Aizawl", "Lunglei", "Saiha", "Champhai"],
  Nagaland: ["Kohima", "Dimapur", "Mokokchung", "Tuensang"],
  Odisha: ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur"],
  Punjab: ["Chandigarh", "Ludhiana", "Amritsar", "Jalandhar", "Patiala"],
  Rajasthan: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner"],
  Sikkim: ["Gangtok", "Namchi", "Gyalshing", "Mangan"],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Salem",
    "Tiruchirappalli",
  ],
  Telangana: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam"],
  Tripura: ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar"],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Agra",
    "Varanasi",
    "Prayagraj",
    "Noida",
  ],
  Uttarakhand: ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Mussoorie"],
  "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri"],
};

export const HEIGHTS = Array.from(
  { length: 31 },
  (_, i) => `${Math.floor(4 + i / 12)}'${i % 12}"`
);
export const WEIGHTS = Array.from({ length: 81 }, (_, i) => `${40 + i} kg`);
